### PR TITLE
Fix deprecated SubfieldBase for Django 1.8+

### PR DESCRIPTION
**Pull request by andreif**

### CODE REVIEW

**Comment by andreif** [comment]
Although, there is probably not much reason to test 1.9+ due to Django getting build-in JSONB field support...

**Comment by andreif** [comment]
@niwinz @nemesisdesign could you do a quick look on it and maybe merge? Master tests fail and this PR should help to fix it

**Comment by nippoo** [comment]
Hey. Is this good to merge? (Or rather, can I start using this branch now?)

**Comment by niwinz** [comment]
I'll merge as soon as I found free time for it! (today or tomorrow).

Sorry for the late response.

**Pull request merged**
