### PR TITLE
Add conf module + make JSON encoder overridable

### PR DESCRIPTION
**Pull request by davidfischer-ch**
And other goodies.

### CODE REVIEW

**Comment by niwibe** [comment]
hi @davidfischer-ch 

thank you very much for your contributions, but you PR implies adding an external dependency and I'm not clearly convinced adding it. The idea of plugable parser is awesome but with appconf dependcy I can not accept the PR as IS.

Can you remove it and use settings directly instead of appconf?

**Comment by davidfischer-ch** [comment]
Hi @niwinz 

I will remove it next week

**Comment by niwinz** [comment]
Great!

**Comment by davidfischer-ch** [comment]
That's it.

**Comment by niwinz** [comment]
Already merged manually! Thanks!

**Pull request closed without merging**
